import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export default function generatePDF() {

  const doc = new jsPDF();

  // Title

  doc.setFontSize(20);

  doc.text(
    "DEPARTMENT OF MICROBIOLOGY",
    20,
    20
  );

  doc.setFontSize(12);

  doc.text(
    "Government Medical College & Hospital, Ramanathapuram",
    20,
    30
  );

  doc.text(
    "Student Academic Performance Report",
    20,
    40
  );

  // Student Info

  doc.setFontSize(14);

  doc.text("Student Details", 20, 55);

  doc.setFontSize(12);

  doc.text("Name: John David", 20, 65);
  doc.text("Register No: MB2025001", 20, 73);
  doc.text("Department: Microbiology", 20, 81);

  // Attendance

  doc.setFontSize(14);

  doc.text("Attendance", 20, 98);

  autoTable(doc, {

    startY: 105,

    head: [["Type", "Attendance %"]],

    body: [

      ["Theory", "92%"],
      ["Practical", "95%"]

    ]

  });

  // FA Marks

  doc.setFontSize(14);

  doc.text(
    "Formative Assessments",
    20,
    doc.lastAutoTable.finalY + 15
  );

  autoTable(doc, {

    startY: doc.lastAutoTable.finalY + 20,

    head: [[
      "FA1",
      "FA2",
      "FA3",
      "FA4",
      "FA5",
      "FA6",
      "FA7",
      "FA8"
    ]],

    body: [[
      "45",
      "42",
      "48",
      "44",
      "46",
      "47",
      "43",
      "49"
    ]]

  });

  // PCT

  doc.setFontSize(14);

  doc.text(
    "Part Completion Tests",
    20,
    doc.lastAutoTable.finalY + 15
  );

  autoTable(doc, {

    startY: doc.lastAutoTable.finalY + 20,

    head: [[
      "PCT1 Theory",
      "PCT1 Practical",
      "PCT2 Theory",
      "PCT2 Practical"
    ]],

    body: [[
      "78",
      "82",
      "80",
      "85"
    ]]

  });

  // Footer

  doc.setFontSize(12);

  doc.text(
    "Generated by Student Academic Performance Portal",
    20,
    280
  );

  // Save PDF

  doc.save("Student_Marksheet.pdf");

}